org: carlosapr01
app: serverless-ec2-schedule-instances
service: aws-python-scheduled-cron-project

frameworkVersion: '3'

package: 
  individually: true
  patterns:
    - "!*/**"
    - "!**"

provider:
  name: aws
  runtime: python3.9

functions:
  rateHandler:
    handler: handler.run
    package: 
      patterns:
        - "hardler.py"
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)
